services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: api:0.2
    env_file:
     - api/.env
    ports:
      - 8080:80
    networks:
      - job_interview

networks:
  job_interview: