"""empty message

Revision ID: 731cdd2b9009
Revises: 7753d327525b
Create Date: 2024-09-08 19:30:51.857229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '731cdd2b9009'
down_revision: Union[str, None] = '7753d327525b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('jobs_user_id_fkey', 'jobs', type_='foreignkey')
    op.drop_constraint('requests_user_id_fkey', 'requests', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('requests_user_id_fkey', 'requests', 'users', ['user_id'], ['id'])
    op.create_foreign_key('jobs_user_id_fkey', 'jobs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
