"""empty message

Revision ID: dfa138a4851b
Revises: 153059f5ea08
Create Date: 2024-09-08 14:54:37.875063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'dfa138a4851b'
down_revision: Union[str, None] = '153059f5ea08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE requests SET status = 'completed' WHERE status IS NULL")
    op.alter_column('requests', 'output',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('requests', 'status',
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'output',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('requests', 'status')
    # ### end Alembic commands ###
